# Numpy

Numerical Python, is a powerful library in Python used for numerical and mathematical operations. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. NumPy is widely used in scientific computing, data analysis, machine learning, and other areas where numerical operations are a central part of the workflow.

## Importing the library

In [1]:
import numpy as np

### Declaring the arrays

In [2]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

### Adding arrays

In [3]:
a1 + a2

array([5, 7, 9])

### Subtracting arrays

In [4]:
a1 - a2

array([-3, -3, -3])

### Multiplying arrays

In [5]:
a1 * a2

array([ 4, 10, 18])

### Dividing arrays

In [6]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

### Accessing the elements of the array by indexing 

In [7]:
a1[2]

3

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])

### ndim - Dimension of the array

In [9]:
a.ndim

2

### itemsize - Byte size of elements

In [10]:
a.itemsize

8

### dtype - Datatype of array

In [11]:
a.dtype

dtype('int64')

### Changing datatype of the array

In [12]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float64)

In [13]:
a.itemsize

8

In [14]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### size - Prints the number of elements in array

In [15]:
a.size

6

### shape - Returns the height and width of the array

In [16]:
a.shape

(3, 2)

### zeros - Create array with all elements with Zero

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones - Create array with all elements with One

In [18]:
np.ones((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### arange - Creates an array with specified Range 

In [19]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [20]:
np.arange(1, 5, 2)

array([1, 3])

### linspace - Generates random numbers of array in Specified Range Linearly

In [21]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### reshape - Change the shape of the array

In [23]:
a.reshape(2, 3)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
a.reshape(6, 1)

array([[1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.]])

### ravel - Flatten the array into one-dimension

In [25]:
a.ravel()

array([1., 2., 3., 4., 5., 6.])

### max and min - Returns Maximum and Minimum elements of array

In [26]:
a.max()

6.0

In [27]:
a.min()

1.0

### sum - Returns sum of all elements in array

In [28]:
a.sum()

21.0

#### axis = 0 Returns sum of elements in column 

In [29]:
a.sum(axis = 0)

array([ 9., 12.])

#### axis = 1 Returns sum of elements in row 

In [30]:
a.sum(axis = 1)

array([ 3.,  7., 11.])

### sqrt - Returns square root of elements in array

In [31]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

### std - Returns standard deviation of elements in array

In [32]:
np.std(a)

1.707825127659933

### indexing and slicing

In [33]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [34]:
# array_name[row, column]
b[1, 2]

6

In [35]:
b[0:2, 2]

array([3, 6])

In [36]:
b[-1]

array([7, 8, 9])

In [37]:
b[-1, 0:2]

array([7, 8])

In [38]:
b[:, 1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

### iterate through numpy arrays

In [39]:
for row in b:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [40]:
for cell in b.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [41]:
c = np.arange(6).reshape(3, 2)
d = np.arange(6, 12).reshape(3, 2)

In [42]:
c

array([[0, 1],
       [2, 3],
       [4, 5]])

In [43]:
d

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

### vstack - Sticking together two array vertically

In [44]:
np.vstack((c, d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### hstack - Sticking together two array horizontally

In [45]:
np.hstack((c, d))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

### hsplit - Split array vertically

In [46]:
e = np.arange(30).reshape(2, 15)

In [47]:
result = np.hsplit(e, 3)

In [48]:
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

### vsplit - Split array horizontally

In [49]:
result = np.vsplit(e, 2)

In [50]:
result

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

### indexing with Boolean array

In [51]:
f = np.arange(12).reshape(3, 4)

In [52]:
g =  f > 4

In [53]:
g

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [54]:
f[g]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
f[g] = -1

In [56]:
f

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [57]:
h = np.arange(12).reshape(3, 4)

### nditer - Iteration through numpy array

#### order C means printing array elements row by row 

In [58]:
for x in np.nditer(h, order = "C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


#### order F means printing array elements column by column

In [59]:
for x in np.nditer(h, order = "F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [60]:
for x in np.nditer(h, order = "F", flags = ["external_loop"]):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [61]:
for x in np.nditer(h, op_flags = ["readwrite"]):
    x[...] = x * x

In [62]:
h

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [63]:
i = np.arange(3, 15, 4).reshape(3, 1)

In [64]:
for x, y in np.nditer([h, i]):
    print(x, y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
